include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/fixtures/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - unawaited_futures
    - unnecessary_lambdas
